name: Create a comment on new issue
on:
  issues:
    types:
      - opened
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: get event context
        run: echo '${{ toJSON(github.event) }}'
      - name: add comment
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: "+GITHUB_TOKEN -d '{"body":"Me too"}' https://api.github.com/repos/OWNER/REPO/issues/ISSUE_NUMBER/comments
        env: 
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
         OWNER: ${{ github.event.repository.owner.login}}
         REPO: ${{ github.event.repository.name}}
         ISSUE_NUMBER: ${{ github.event.issue.id}}
         
         
       
